version: '2'
services:
  ripper:
    build: radioRipper
    volumes:
      - ./radioRipper/:/radioRipper
  player:
    build: serverplaylist/
    volumes:
      - ./radioRipper/music/:/var/www/mp3/music
    ports:
      - "127.2.2.2:2080:80"

