version: '2'
services:
  ripper:
    build: radioRipper
    volumes:
      - ./radioRipper/:/radioRipper
      - music1:/radioRipper/music
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
  player:
    build: serverplaylist/
    volumes:
      - music1:/var/www/mp3/music
    ports:
      - "127.2.2.2:2080:80"
volumes:
  music1:

